name: Build CEdev Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install GCC and Make
      - name: Install GCC and Make
        run: |
          sudo apt update
          sudo apt install -y build-essential unzip

      # Step 3: Set project name
      - name: Set project folder
        run: |
          PROJECT_NAME="shapes"
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      # Step 4: Set paths for CEdev tools, includes, and libraries
      - name: Setup CEdev environment
        run: |
          # Add CEdev/bin to PATH so make can find cedev-config
          export PATH=$PATH:$GITHUB_WORKSPACE/bin
          # Set C compiler include path
          export C_INCLUDE_PATH=$GITHUB_WORKSPACE/include:$C_INCLUDE_PATH
          # Set library paths
          export LIBRARY_PATH=$GITHUB_WORKSPACE/lib:$LIBRARY_PATH
          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib:$LD_LIBRARY_PATH
          # Persist environment for later steps
          echo "PATH=$PATH:$GITHUB_WORKSPACE/bin" >> $GITHUB_ENV
          echo "C_INCLUDE_PATH=$GITHUB_WORKSPACE/include:$C_INCLUDE_PATH" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$GITHUB_WORKSPACE/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      # Step 5: Build the project using its Makefile
      - name: Build project
        run: |
          cd Projects/$PROJECT_NAME
          make

          
      # Step 6: Upload the compiled .8xp binary
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: project-binary
          path: Projects/$PROJECT_NAME/bin/*.8xp
